### ISSUE TITLE
Your autosave charts will crash in the chart editor when you load them.

### ISSUE THREAD

**Issue by Fixthebug307** [jigsaw-4277821/PE-0.5.1-Android#2]
### Describe your bug here.

Save your chart, then load autosave. It will crash.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

I didn't edit anything, I simply ported this apk from earlier.

**Comment by Randomxdp** [comment]
I think he fixed it
